### ISSUE TITLE
Develop Link is not working 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-for-the-Humanities-at-Temple#3]
The develop link for CHAT is not working.. 
![image](https://user-images.githubusercontent.com/15130721/46616307-3f6afe00-cae8-11e8-9fef-8dbd303d85a1.png)

**Comment by tu-chill** [comment]
@lidopaglia can you help us with this? 

https://github.com/TULiberalArts/Center-for-the-Humanities/issues/3

**Comment by lidopaglia** [comment]
@tu-chill looks like there is a [YAML syntax error](https://travis-ci.org/TULiberalArts/Center-for-the-Humanities/jobs/438714671#L656) in the front matter for [pages/home.md](https://raw.githubusercontent.com/TULiberalArts/Center-for-the-Humanities/master/pages/home.md). That explains why there is no index.html pushed to S3.

Should be fixed in 52114944cfd0b22e2ece952711ae8a2421ab247b
